@{
    psake        = 'latest'
    Pester       = ''        # Same as latest
    BuildHelpers = '0.0.20'  # I don't trust this Warren guy...
    PSDeploy     = '0.1.21'  # Maybe pin the version in case he breaks this...
}